# Generated by Django 5.1.2 on 2025-02-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_details_filled',
            field=models.BooleanField(default=False),
        ),
    ]
