# Generated by Django 5.1.2 on 2025-03-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_additional_details_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('working', 'Working Professional')], max_length=20),
        ),
    ]
