# Generated by Django 5.1.2 on 2025-06-23 11:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='profile_pics/default.png', max_length=255, verbose_name='image'),
        ),
    ]
