# Generated by Django 5.1.2 on 2025-02-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='file',
        ),
        migrations.AddField(
            model_name='postfile',
            name='file_data',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='file_size',
            field=models.IntegerField(),
        ),
    ]
