# Generated by Django 5.1.2 on 2025-02-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postnote_main_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnote',
            name='main_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
