# Generated by Django 5.1.2 on 2025-02-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_commentreport_commentvote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentReport',
        ),
        migrations.DeleteModel(
            name='CommentVote',
        ),
    ]
