# Generated by Django 5.1.2 on 2025-02-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_commentreport_commentvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreport',
            name='resolved',
        ),
        migrations.AddField(
            model_name='commentreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abuse/Harassment'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='vote_type',
            field=models.IntegerField(default=1),
        ),
    ]
