# Generated by Django 5.1.2 on 2025-02-18 19:06

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_commentreport_resolved_commentreport_status_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postnote',
            name='tags',
        ),
        migrations.AddField(
            model_name='postnote',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Enter tags separated by commas', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
