# Generated by Django 5.1.2 on 2025-02-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_postnote_tags_postnote_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postnote',
            name='tags',
        ),
        migrations.AddField(
            model_name='postnote',
            name='tags',
            field=models.CharField(help_text='Separate tags with commas', max_length=255, null=True),
        ),
    ]
