# Generated by Django 5.1.2 on 2025-02-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_postnote_tags_postnote_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnote',
            name='category',
            field=models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('astronomy', 'Astronomy'), ('environmental_science', 'Environmental Science'), ('mathematics', 'Mathematics'), ('computer_science', 'Computer Science'), ('engineering', 'Engineering'), ('information_technology', 'Information Technology'), ('artificial_intelligence', 'Artificial Intelligence'), ('data_science', 'Data Science'), ('history', 'History'), ('arts', 'Arts'), ('literature', 'Literature'), ('business', 'Business'), ('health_wellness', 'Health & Wellness'), ('language', 'Language'), ('travel_culture', 'Travel & Culture'), ('personal_development', 'Personal Development'), ('hobbies', 'Hobbies'), ('education', 'Education'), ('politics', 'Politics'), ('philosophy', 'Philosophy'), ('psychology', 'Psychology'), ('food_cooking', 'Food & Cooking'), ('sports_fitness', 'Sports & Fitness'), ('entertainment', 'Entertainment'), ('design', 'Design'), ('spirituality', 'Spirituality'), ('parenting', 'Parenting'), ('other', 'Other')], max_length=50),
        ),
    ]
