# Generated by Django 5.1.2 on 2025-03-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_notesummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteSummary',
        ),
    ]
