# Generated by Django 5.1.2 on 2025-03-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_notesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesummary',
            name='summary_type',
            field=models.CharField(choices=[('brief', 'Brief'), ('detailed', 'Detailed')], default='brief', max_length=10),
        ),
    ]
