# Generated by Django 5.1.2 on 2025-04-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_quizgeneration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteSummary',
        ),
    ]
