# Generated by Django 5.1.2 on 2025-04-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_postnote_star_count_alter_postnote_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postnote',
            name='star_count',
        ),
    ]
