# Generated by Django 5.1.2 on 2025-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('star', 'Star on Note'), ('comment', 'Comment on Note'), ('following', 'Following'), ('followed', 'Followed'), ('comment_like', 'Like on Comment'), ('comment_reply', 'Reply to Comment')], max_length=20),
        ),
    ]
